/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./../src/components/BaseLayout.vue')['default']
    Dashboard: typeof import('./../src/components/Dashboard.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderNav: typeof import('./../src/components/HeaderNav.vue')['default']
    Layout: typeof import('../src/components/BaseLayout.vue')['default']
    OButton: typeof import('onu-ui')['OButton']
    OText: typeof import('onu-ui')['OText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../src/components/SideMenu.vue')['default']
    TheFooter: typeof import('./../src/components/TheFooter.vue')['default']
    TheInput: typeof import('./../src/components/TheInput.vue')['default']
    TheStudy: typeof import('./../src/components/TheStudy.vue')['default']
    UserForm: typeof import('./../src/components/UserForm.vue')['default']
    UserSearch: typeof import('./../src/components/UserSearch.vue')['default']
    UserTable: typeof import('./../src/components/UserTable.vue')['default']
    WorkForm: typeof import('./../src/components/WorkForm.vue')['default']
    WorkSearch: typeof import('./../src/components/WorkSearch.vue')['default']
    WorkTable: typeof import('./../src/components/WorkTable.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
